import type { ErrorComponentProps } from "@tanstack/react-router";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Outlet, Link, createRootRouteWithContext, useRouter, HeadContent, Scripts } from "@tanstack/react-router";
import { useEffect, type ReactNode } from "react";
import appCss from "../styles.css?url";
import { reportLovableError } from "../lib/lovable-error-reporting";
import { SiteFooter, SiteHeader, WhatsAppWidget } from "@/components/site/layout";
import { Button } from "@/components/ui/button";

function NotFoundComponent(){return <div className="grid min-h-screen place-items-center bg-muted px-5"><div className="text-center"><p className="eyebrow">Page not found</p><h1 className="mt-3 font-display text-7xl font-bold text-brand-navy">404</h1><p className="mt-4 text-muted-foreground">The page you requested is not available.</p><Button asChild variant="gold" className="mt-6"><Link to="/">Return home</Link></Button></div></div>}
function ErrorComponent({error,reset}:ErrorComponentProps){const router=useRouter();useEffect(()=>{reportLovableError(error,{boundary:"tanstack_root_error_component"})},[error]);return <div className="grid min-h-screen place-items-center px-5"><div className="text-center"><h1 className="font-display text-3xl font-bold text-brand-navy">This page didn’t load</h1><p className="mt-3 text-muted-foreground">Please try again or return home.</p><div className="mt-6 flex justify-center gap-3"><Button onClick={()=>{router.invalidate();reset()}}>Try again</Button><Button asChild variant="outline"><Link to="/">Go home</Link></Button></div></div></div>}
export const Route=createRootRouteWithContext<{queryClient:QueryClient}>()({head:()=>({meta:[{charSet:"utf-8"},{name:"viewport",content:"width=device-width, initial-scale=1"},{name:"author",content:"Asihwebe Foundation"},{property:"og:type",content:"website"},{property:"og:site_name",content:"Asihwebe Foundation"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"preconnect",href:"https://fonts.googleapis.com"},{rel:"preconnect",href:"https://fonts.gstatic.com",crossOrigin:"anonymous"},{rel:"stylesheet",href:"https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&family=Sora:wght@600;700;800&display=swap"},{rel:"stylesheet",href:appCss},{rel:"icon",type:"image/png",href:"/favicon.png"}]}),shellComponent:RootShell,component:RootComponent,notFoundComponent:NotFoundComponent,errorComponent:ErrorComponent});
function RootShell({children}:{children:ReactNode}){return <html lang="en"><head><HeadContent/></head><body>{children}<Scripts/></body></html>}
function RootComponent(){const{queryClient}=Route.useRouteContext();return <QueryClientProvider client={queryClient}><a href="#main-content" className="skip-link">Skip to content</a><SiteHeader/><main id="main-content"><Outlet/></main><SiteFooter/><WhatsAppWidget/></QueryClientProvider>}
