import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CTA, PageHero, Pathway, SectionHeading } from "@/components/site/sections";
import { programmes } from "@/lib/site-content";
import { BgrJourney } from "@/components/site/bgr-journey";

export const Route=createFileRoute("/programmes")({head:()=>({meta:[{title:"Enterprise & Community Development Programmes | Asihwebe"},{name:"description",content:"Explore Asihwebe Foundation impact areas and TRDEA, its township and rural enterprise development flagship programme in South Africa."},{property:"og:title",content:"Asihwebe Programmes | Enterprise and Digital Enablement"},{property:"og:description",content:"Practical impact areas and a flagship programme supporting entrepreneurs, small businesses and communities."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/programmes"}]}),component:Programmes});

function Programmes(){return <><PageHero eyebrow="Programmes" title="From impact areas to practical delivery" copy="Our impact areas define where Asihwebe focuses. Structured programmes turn those priorities into practical pathways for entrepreneurs, small businesses and communities."/><section className="section-pad"><div className="site-container"><SectionHeading eyebrow="Our impact areas" title="Four connected areas of development" copy="These areas guide programme design and allow new initiatives to be added as community priorities and partnerships evolve."/><div className="mt-10 space-y-3">{programmes.map(({title,description,icon:Icon},i)=><article key={title} className="grid gap-6 border border-border p-6 md:grid-cols-[4rem_1fr_1.2fr] md:items-center"><span className="grid size-12 place-items-center rounded-sm bg-brand-gold-soft text-brand-orange"><Icon/></span><div><p className="text-xs font-bold text-brand-orange">IMPACT AREA {String(i+1).padStart(2,"0")}</p><h2 className="mt-1 font-display text-2xl font-bold text-brand-navy">{title}</h2></div><p className="leading-7 text-muted-foreground">{description}</p></article>)}</div></div></section><section className="section-pad bg-brand-navy"><div className="site-container"><div className="grid gap-8 lg:grid-cols-[1fr_.7fr] lg:items-end"><SectionHeading light eyebrow="Flagship Asihwebe initiative" title="Township & Rural Digital Enterprise Accelerator" copy="TRDEA combines practical enterprise development with digital enablement to help township and rural entrepreneurs become more market-ready and connected to opportunity."/><div className="flex flex-wrap gap-3 lg:justify-end"><Button asChild variant="gold"><Link to="/trdea">Explore TRDEA<ArrowRight/></Link></Button><Button asChild variant="heroOutline"><Link to="/partnerships">Partner With TRDEA</Link></Button></div></div><Pathway/><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{["Entrepreneur registration and profiling","Business orientation","Digital business profiling","Digital payment enablement","Online marketplace participation","Practical business workshops","Market access","Growth support","Monitoring and evaluation"].map(item=><p key={item} className="flex gap-2 text-sm text-primary-foreground/75"><Check className="mt-0.5 size-4 shrink-0 text-brand-gold"/>{item}</p>)}</div></div></section><BgrJourney/><CTA title="Interested in programme participation or delivery?" copy="Tell us about your community, organisation or enterprise-development priorities."/></>}