import { Link, useRouterState } from "@tanstack/react-router";
import { ChevronDown, Linkedin, Mail, MapPin, Menu, MessageCircle, X } from "lucide-react";
import { links } from "@/lib/site-content";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Brand } from "./brand";

const nav = [["Home", "/"], ["About Us", "/about"], ["Programmes", "/programmes"], ["Partnerships", "/partnerships"], ["Impact", "/impact"], ["Contact", "/contact"]] as const;
const programmeLinks = ["Enterprise Development", "Digital Enablement", "Skills & Capacity Development", "Community Activation"];

export function SiteHeader() {
  const [open,setOpen]=useState(false); const pathname=useRouterState({select:s=>s.location.pathname});
  return <header className="sticky top-0 z-50 border-b border-brand-navy/10 bg-background/95 backdrop-blur"><div className="site-container flex min-h-20 items-center justify-between gap-5 py-2"><Brand/><nav className="hidden items-center gap-0.5 lg:flex" aria-label="Primary navigation">{nav.map(([label,to])=>label==="Programmes"?<div key={to} className="group relative"><Link to={to} className={`nav-link inline-flex items-center gap-1 ${pathname===to||pathname==="/trdea"?"nav-link-active":""}`}>{label}<ChevronDown className="size-3.5"/></Link><div className="invisible absolute left-0 top-full w-72 border border-border bg-background p-2 opacity-0 shadow-lg transition group-hover:visible group-hover:opacity-100 group-focus-within:visible group-focus-within:opacity-100"><Link to="/programmes" className="block border-b px-3 py-2 text-sm font-bold text-brand-navy">All impact areas</Link>{programmeLinks.map(item=><Link key={item} to="/programmes" className="block px-3 py-2 text-sm text-muted-foreground hover:bg-muted hover:text-brand-navy">{item}</Link>)}<Link to="/trdea" className="block border-t px-3 py-2 text-sm font-bold text-brand-orange">TRDEA flagship programme</Link></div></div>:<Link key={to} to={to} className={`nav-link ${pathname===to?"nav-link-active":""}`}>{label}</Link>)}</nav><div className="hidden lg:block"><Button asChild variant="gold"><Link to="/partnerships">Partner With Us</Link></Button></div><Button variant="ghost" size="icon" className="lg:hidden" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label={open?"Close menu":"Open menu"}>{open?<X/>:<Menu/>}</Button></div>{open&&<nav className="border-t bg-background px-5 py-5 lg:hidden" aria-label="Mobile navigation"><div className="mx-auto flex max-w-xl flex-col gap-1">{nav.map(([label,to])=><div key={to}><Link to={to} onClick={()=>setOpen(false)} className="block rounded-sm px-3 py-3 font-semibold text-brand-navy hover:bg-muted">{label}</Link>{label==="Programmes"&&<Link to="/trdea" onClick={()=>setOpen(false)} className="ml-5 block border-l border-brand-gold px-3 py-2 text-sm font-semibold text-brand-orange">TRDEA flagship programme</Link>}</div>)}<Button asChild variant="gold" className="mt-3"><Link to="/partnerships" onClick={()=>setOpen(false)}>Partner With Us</Link></Button></div></nav>}</header>;
}

export function SiteFooter(){const links=[["Home","/"],["About Us","/about"],["Programmes","/programmes"],["TRDEA","/trdea"],["Partnerships","/partnerships"],["Impact","/impact"],["Contact","/contact"],["Support Our Work","/support"]] as const;return <footer className="bg-brand-navy text-primary-foreground"><div className="site-container grid gap-10 py-14 md:grid-cols-[1.4fr_1fr_1fr]"><div><Brand inverse/><p className="mt-5 max-w-sm text-sm leading-6 text-primary-foreground/70">Empowering Communities. Enabling Opportunity. Shaping Futures.</p></div><div><h2 className="footer-heading">Navigate</h2><div className="grid grid-cols-2 gap-x-6 gap-y-3">{links.map(([label,to])=><Link key={to} to={to} className="text-sm text-primary-foreground/70 hover:text-brand-gold">{label}</Link>)}</div></div><div><h2 className="footer-heading">Contact</h2><p className="footer-line"><MapPin/>South Africa</p><a className="footer-line hover:text-brand-gold" href="mailto:info@asihwebe.org.za"><Mail/>info@asihwebe.org.za</a><a className="footer-line hover:text-brand-gold" href={links.linkedin} target="_blank" rel="noopener noreferrer"><Linkedin/>Connect With Us on LinkedIn<span className="sr-only"> (opens in a new tab)</span></a><a className="footer-line hover:text-brand-gold" href={links.whatsapp} target="_blank" rel="noopener noreferrer"><MessageCircle/>Chat on WhatsApp<span className="sr-only"> (opens in a new tab)</span></a></div></div><div className="border-t border-primary-foreground/15"><div className="site-container flex flex-col gap-3 py-5 text-xs text-primary-foreground/60 sm:flex-row sm:items-center sm:justify-between"><p>© 2026 Asihwebe Foundation. All rights reserved.</p><div className="flex gap-5"><Link to="/privacy">Privacy Policy</Link><Link to="/terms">Website Terms</Link></div></div></div></footer>}

export function WhatsAppWidget(){return <a href={links.whatsapp} target="_blank" rel="noopener noreferrer" aria-label="Chat with Asihwebe Foundation on WhatsApp (opens in a new tab)" className="fixed bottom-4 right-4 z-40 inline-flex size-12 items-center justify-center rounded-full bg-whatsapp text-primary-foreground shadow-lg transition hover:scale-105 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-brand-gold sm:bottom-6 sm:right-6"><svg viewBox="0 0 24 24" className="size-6" fill="currentColor" aria-hidden="true"><path d="M17.47 14.38c-.3-.15-1.76-.87-2.03-.97-.27-.1-.47-.15-.67.15-.2.3-.77.97-.94 1.17-.17.2-.35.22-.64.07-.3-.15-1.26-.46-2.4-1.48-.89-.79-1.49-1.77-1.66-2.07-.17-.3-.02-.46.13-.61.13-.13.3-.35.45-.52.15-.17.2-.3.3-.5.1-.2.05-.37-.02-.52-.08-.15-.67-1.62-.92-2.22-.24-.58-.49-.5-.67-.51h-.57c-.2 0-.52.07-.79.37-.27.3-1.04 1.02-1.04 2.48 0 1.46 1.07 2.88 1.21 3.08.15.2 2.1 3.2 5.08 4.49.71.31 1.26.49 1.7.63.71.23 1.36.2 1.87.12.57-.09 1.76-.72 2-1.41.25-.7.25-1.29.17-1.41-.07-.13-.27-.2-.57-.35zM12.05 21.5h-.01a9.46 9.46 0 0 1-4.82-1.32l-.35-.21-3.58.94.96-3.49-.23-.36a9.43 9.43 0 0 1-1.45-5.03c0-5.22 4.25-9.47 9.48-9.47a9.4 9.4 0 0 1 6.7 2.78 9.4 9.4 0 0 1 2.77 6.7c0 5.22-4.25 9.46-9.47 9.46zm8.06-17.53A11.33 11.33 0 0 0 12.05.63C5.77.63.66 5.73.66 12.01c0 2 .52 3.96 1.52 5.69L.57 23.6l6.04-1.58a11.37 11.37 0 0 0 5.44 1.38h.01c6.27 0 11.38-5.1 11.38-11.38 0-3.04-1.18-5.9-3.33-8.05z"/></svg></a>}
